#Code for plotting regional outputs
#generated by Tutorial05
print("Starting script...")
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

# Import obs data
dat = pd.read_csv("./outputs/6.areal_statistics/Areal_statistics.csv")
dat['time']=pd.to_datetime(dat['time'])
pltThese = (dat['memberID'] =='ensstats') & (dat['percentiles'] ==50) & \
            (dat['srcID']=='CORDEX') & (dat['expt']=='rcp85')
selDat=dat[pltThese]

#Import shapefile
shp = gpd.GeoDataFrame.from_file("docs/tutorials/Tutorial05_files/Ghana_regions.shp")
shp['area']=shp['ADM1_PCODE']

#Merge datasets
pltDat = pd.merge(shp,selDat,how="right",on='area')

#Setup plots
fig, axes = plt.subplots(1, 2, figsize=(20, 10))
vmin = min(pltDat['mean'].min(), pltDat['mean'].min())
vmax = max(pltDat['mean'].max(), pltDat['mean'].max())
cmap = 'viridis'  # Common colormap

#Make plot 1
thisDat= pltDat[pltDat['periodID']==1]
thisDat.plot(column='mean',
             cmap=cmap,              
             vmin=vmin, vmax=vmax,  # Set common color scale             
             edgecolor="black",
             ax=axes[0])  
axes[0].set_title("1981-2010", fontsize=16)

#Make plot 2
thisDat= pltDat[pltDat['periodID']==4]
thisDat.plot(column='mean',
             cmap=cmap,              
             vmin=vmin, vmax=vmax,  # Set common color scale             
             edgecolor="black",
             ax=axes[1])  
axes[1].set_title("2071-2100 (RCP8.5)", fontsize=16)

#Add colour bar
sm = plt.cm.ScalarMappable(cmap=cmap, norm=mcolors.Normalize(vmin=vmin, vmax=vmax))
sm._A = []  # Dummy array for the colorbar
cbar = fig.colorbar(sm, ax=axes, orientation='horizontal', fraction=0.05, pad=0.05)
cbar.set_label("Mean Annual Temperature (K)", fontsize=12)

#Save file
plt.savefig("Tutorial05.png", format="png", 
            dpi=300, bbox_inches="tight")

#Finish
print("Script succesfully completed.")