#Code for comparing calibrated and uncalibrated indicators
#generated by Tutorial06
print("Starting script...")
import pandas as pd
from plotnine import *

# For obs data
dat = pd.read_csv("./outputs/6.areal_statistics/Areal_statistics.csv")
dat['lbl']=dat['srcID']+"-"+dat['indID']
dat['time']=pd.to_datetime(dat['time'])
pltThese = (dat['memberID'] =='ensstats') & (dat['percentiles'] ==50) & (dat['expt'].isin(['rcp85','no-expt']))
pltdat=dat[pltThese]

#Make plot
p= (ggplot(pltdat, aes(x="time", y="mean", colour="lbl"))
+ geom_point()
 + labs(
     x="",
     y="Mean temperature",
     title="Effect of calibration (for RCP8.5)",
     colour="Data source",
 )
 + theme_bw()
 + scale_x_datetime(date_labels="%Y")
 + theme(legend_position="bottom")
)

#Save file
p.save("Tutorial06.png",
    verbose=False)

#Finish
print("Script succesfully completed.")