print()
print("=" * 70)
print("                         Welcome to KAPy")
print("=" * 70)
print()
print("KAPy (Klimaatlas in Python) is a pipeline for producing climate")
print("data for use in climate services using reproducible, automated workflows.") 
print()
print("This setup will create a new KAPy project for you. The project")
print("contains your own configuration, input and output directories,")
print("and a Snakefile for running the workflow. The KAPy framework")
print("itself is included as a Git submodule, so that it can be managed")
print("and updated independently of your project.")
print()
print("You will now be asked a few questions to configure your project.")
print()
print("Project name")
print("  The human-readable name of your new project.")
print()
print("Project slug")
print("  A simplified version of the project name used as the project")
print("  directory name. It is generated automatically from the project")
print("  name, using lowercase letters and underscores.")
print()
print("Project description")
print("  A short description of the purpose of your project. This will")
print("  be included in the generated README.")
print()
print("Use full configuration")
print("  Choose between a basic KAPy configuration and a full")
print("  configuration. The standard configuration provides")
print("  the basic setup, while the full configuration includes all")
print("  configuration options that KAPy supports.")
print()
print("Download sample dataset")
print("  Choose whether to download a sample dataset and unpack it")
print("  into the inputs/ directory. This dataset is used")
print("  to demonstrate the use of KAPy, and is not required for")
print("  running the workflow.")
print()
print("-" * 70)
print()

