# KAPy testing configuration
#
# This configuration provides a configuration with all features of KAPy turned on.
# It is intended to be a complement to the minimum working example in ./config/
# showing how everything in KAPy is configured, and also to be used as a test suite.
# https://download.dmi.dk/Research_Projects/KAPy/tas_example_dataset.zip
#
# This configuration can be used directly with the following command
# snakemake --configfile workflow/testing/config.yaml ... 


configurationTables:
    inputs:  'workflow/testing/inputs.tsv'
    indicators: 'workflow/testing/indicators.tsv'
    secondaryVars: 'workflow/testing/secondaryVars.tsv'
    biasAdjustment: 'workflow/testing/biasAdjustment.tsv'
    tertiaryVars: 'workflow/testing/tertiaryVars.tsv'
    periods:  'workflow/testing/periods.tsv'
    seasons: 'workflow/testing/seasons.tsv'
dirs:
    primaryVariables: 'testing/01.primaryVars'
    secondaryVariables: 'testing/02.secondaryVars'
    biasAdjustment: 'testing/03.biasAdjustment'
    tertiaryVariables: 'testing/04.tertiaryVars'
    indicators: 'testing/05.indicators'
    regridded: 'testing/06.commmon_grid'
    ensstats: 'testing/07.ensstats'
    arealstats: 'testing/08.areal_statistics'
    outputs: 'testing/09.outputs'
    tempDir: 'testing/tmp'
outputs:
    ensembleStatisticsCSV: 'Ensemble_statistics.csv'
    ensembleMembersCSV: 'Ensemble_members.csv'
    database: 'KAPy_outputs.sqlite'

# Configuration options------------------------------------
arealstats:
    useAreaWeighting: True
    shapefile: 'docs/tutorials/Tutorial05_files/Ghana_regions.shp'
cutouts:
    method: 'lonlatbox'  #'none'
    xmin: -4
    xmax: 2
    ymin: 4
    ymax: 12
ensembles:
    percentiles: [10,50,90]
    method: "linear"
outputGrid:
    templateType: 'cdo'
    gridName: 'Ghana025'
    method: 'bilinear'
    path: 'workflow/testing/griddes.txt'
    
