---
title: "KAPy download status"
date: " `r Sys.time() `"
output: 
  html_notebook:
    code_folding: hide
editor_options: 
  chunk_output_type: inline
---

This notebook provides an overview of the status of file downloads. It compares the files identified for download (in the "URLs" folder) with those that have actually been downloaded. Summary statistics are then generated, so that we can see what is missing and where.

```{r setup, warning=FALSE,message=FALSE}
#Load packages 
library(tidyverse)
library(yaml)
library(here)
library(knitr)

#Set defaults
knitr::opts_chunk$set(echo = FALSE)

#Import config file
#Need to handle the defaults as well
config <- read_yaml(here("config.yaml"))
dft <- read_yaml(here("configs/defaults.yaml"))
cfg <- modifyList(dft,config)

#Get filelists
URLs <- 
  tibble(path=dir(here(cfg$dirs$outputDir,cfg$dirs$URLs),pattern=".url$",full.names = TRUE)) %>% 
  mutate(ncfile=gsub(".url","",basename(path)),
         URL=map_chr(path,readLines,warn=FALSE))
downloaded <-
  tibble(path=dir(here(cfg$dirs$outputDir,cfg$dirs$modelInputs),pattern=".nc$",full.names = TRUE)) %>% 
  mutate(fname=basename(path))

#Merge and process filelists
status <- 
  URLs %>% 
  select(-path) %>% 
  mutate(downloaded=ncfile %in% downloaded$fname) %>% 
  mutate(fields=gsub(".nc$","",ncfile)) %>% 
  separate_wider_delim(fields,
                       names=c('VariableName', 'Domain', 'GCMModelName', 'CMIP5ExperimentName', 
                              'CMIP5EnsembleMember','RCMModelName', 'RCMVersionID', 'Frequency', 'Time'),
                       delim="_") %>% 
  #Extract the server from the URL, so that we can see which servers are missing
  extract(URL,"server","https?://([^/]+)/.+",remove=FALSE) 

#Summary function
#Makes a pretty output summary table. Input table, d, is already grouped appropriately
showSum <- function(d) {
  d %>% 
  summarise(percent_missing=mean(!downloaded)*100,
            missing=sum(!downloaded),
            total=length(downloaded),
            .groups = "drop") %>% 
  arrange(desc(percent_missing)) %>% 
  kable()
}

```

# Overview 

```{r}
status %>% 
  showSum()
```
 
# By variable and time resolution
 
```{r}
status %>% 
  group_by(VariableName,Frequency) %>% 
  showSum()  
```

# By scenario

```{r}
status %>% 
  group_by(VariableName,CMIP5ExperimentName) %>% 
  showSum()

```

 
# By server
 
```{r}
status %>% 
  group_by(server) %>% 
  showSum()
```
 
 

