---
title: "Klimaatlas Ghana"
author: "Mark R. Payne, mapa@dmi.dk"
date: " `r Sys.time() `"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

This Notebook shows the first results from Klimaatlas Ghana (KAGH). Results are preliminary, and have not been quality checked. 

```{r setup}
#Load packages 
library(tidyverse)
library(tidync)
library(here)

#Set defaults
knitr::opts_chunk$set(echo = FALSE)

#Import dataset metadata
datAll <-
  tibble(path=dir(here("..","scratch","6.ensstat"),pattern="*.nc",full.names = TRUE),
         fname=basename(path)) %>% 
  separate_wider_regex(fname,c("^i",ind="[0-9]+","_ensstat_",scenario=".+",".nc") ) 

```

## Mean Annual Temperature

```{r}
#Import data sets
thisDat <- 
  datAll %>% 
  filter(ind==101) %>% 
  mutate(dat=map(path,~ tidync(.x) %>% activate("D2,D1,D0") %>% hyper_tibble())) %>% 
  unnest(dat) %>% 
  select(scenario,lon,lat,period,starts_with("i101"))

#Calculate time series averages
tsDat <- 
  thisDat %>% 
  select(scenario,lon,lat,period,starts_with("i101_p")) %>% 
  pivot_longer(starts_with("i101")) %>% 
  mutate(name=gsub("i101_","",name)) %>% 
  group_by(scenario,period,name) %>% 
  summarise(value=mean(value)-273.15,
            .groups="drop") %>% 
  pivot_wider()#names_from="name",values_from="value")

#Get reference value and correct 
ref <-
  tsDat %>% 
  filter(period==1) %>% 
  pivot_longer(-c("scenario","period")) %>% 
    group_by(name) %>% 
    summarise(value=mean(value)) %>% 
    pivot_wider()

pltDat <-
  tsDat %>% 
  mutate(p90=p90-ref$p50,
         p50=p50-ref$p50,
         p10=p10-ref$p50)

#Make a plot
ggplot() +
  geom_hline(yintercept=0,col="grey50" )+
  geom_boxplot(data=filter(pltDat,period!=1),
               mapping=aes(x=factor(period),ymin=p10,lower=p10,middle=p50,ymax=p90,upper=p90,
                           fill=scenario,group=paste(scenario,period)),
               width=0.5,
               stat="identity")+
  theme_bw()+
  theme(legend.position = "bottom")+
  labs(x="",y="Change in annual mean temperature (⁰C)",
       fill="Scenario",
       caption=sprintf("Reference: %2.1f⁰C",ref$p50 ))+
  scale_fill_manual(values=c(rcp85=rgb(150,34, 36,255,maxColorValue = 255),
                             rcp45=rgb(235,143, 55,255,maxColorValue = 255),
                             rcp26=rgb(33,61, 108,255,maxColorValue = 255)))+
  scale_x_discrete(breaks = 2:4,
                    labels = c("Start-of-century\n(2011-2040)",
                               "Mid-century\n(2041-2070)",
                               "End-of-century\n(2071-2100)"))

```


Spatial anomaly pattern at the end of the century (2071-2100)

```{r}
#Now make a spatial plot
histDat <-
  thisDat %>% 
  filter(period==1) %>% 
  select(scenario,lon,lat,p50=i101_p50)

eocDat <-
  thisDat %>% 
  filter(period==4) %>% 
  select(scenario,lon,lat,p50=i101_p50)

spDat <- 
  left_join(histDat,eocDat,by=c("scenario","lon","lat"),
            suffix=c(".hist",".eoc")) %>% 
  mutate(anom=p50.eoc-p50.hist)

ggplot(spDat,aes(lon,lat,fill=anom))+
  facet_wrap(~ scenario)+
  geom_raster()+
  theme_bw()+
  scale_fill_distiller(type="div",palette = "RdBu",limits=c(-5,5))+
  annotation_map(map_data("world"),fill=NA,colour="black")+
  labs(x="",y="",fill="Anomaly\n(⁰C)")+
  scale_x_continuous(expand=c(0,0))+
  scale_y_continuous(expand=c(0,0))

```

