# Snakemake profile that can be used to set defaults and customise resource useage
#
# For details of the use of profiles, see the snakemake documentation:
# https://snakemake.readthedocs.io/en/stable/executing/cli.html#profile-yaml-files
#
# Here we use a YAML trick with an anchor and aliases so that we only need to define resources and threads once,
# and then reuse them in other rules. Note that if we want to override part of a rule, we can use a 
# merge instead e.g.
# _03_biasAdjustment_tas-ba:
#   <<: *LocalCluster
#   mem_mb: 4000          # override just this one key
# Remember though that we need to define the rules and resources for each rule by hand. There is
# no mechanism to do this more efficiently.

# Run-time configuration -----------------------------
rerun-incomplete: true
keep-going: false

# Resources made available to the entire KAPy pipeline
cores: 10
resources:
  mem_mb: 5000

# Rule configuration -----------------------
set-defaults:
  #tmpdir: /scratch/

set-threads: 
  #Default threads for rules using dask
  dask_threads: &dask_threads 2
  #Rules using dask.
  _03_biasAdjustment_tasK-ba: *dask_threads
  _03_biasAdjustment_tas-ba: *dask_threads

set-resources:
  #Default resources used by dask
  dask_resources: &dask_resources
    dask: localCluster
    mem_mb: 2000
    threads_per_worker: 1
    memory_limit: 1000MB
  #Rules using dask
  _03_biasAdjustment_tasK-ba: *dask_resources
  _03_biasAdjustment_tas-ba: *dask_resources

