# KAPy minimum working example
#
# This configuration provides a minimum working example of a KAPy configuration, 
# performing the simplest version of a KAPy pipeline (primaryVars, one indicator,
# areal statistics and outputs). The file can also be used as a template to build 
# up your own custom configuration.  More details can be found in the GitHub 
# documentation and the tutorials, most of which use this configuration as a point of departure.
#
# The config also assumes the presence of the tutorial dataset, which can be downloaded
# from https://download.dmi.dk/Research_Projects/KAPy/tas_example_dataset.zip
# See Tutorial 01 in particular for more information
# 
# For a more complete configuration, taking advantage of all features, see the configuration
# in ./workflow/testing

output_directory: "outputs"
configuration_tables:
    periods:  'config/periods.tsv'
    seasons: 'config/seasons.tsv'
    inputs:  'config/inputs.tsv'
    indicators: 'config/indicators.tsv'
    secondary_variables: ''   
    bias_adjustment: '' 
    tertiary_variables: ''  


# Configuration options------------------------------------
areal_statistics:
    ensemble_areal_statistics: True
    member_areal_statistics: False
    use_area_weighting: False
    shapefile: # leave empty for "none" 
cutouts:
    method: 'lonlatbox'  #'none'
    xmin: -4
    xmax: 2
    ymin: 4
    ymax: 12
ensembles:
    percentiles: [0,50,100]  #Use full data range due to small ensemble size.
    method: "linear"
output_grid:
    template_type: 'none' #cdo'
    grid_name: 'Ghana025'
    method: 'bilinear'
    path: 'config/griddes.txt'

# Advanced options-------------
dask_resources:  #Blank to use default options. Generally specified at runtime via: --config dask_resources=<path/to/file.tsv>

