# Code for plotting regional outputs
# Generated by Tutorial 7

print("Starting script...")

import sqlite3

import geopandas as gpd
import matplotlib.colors as mcolors
import matplotlib.pyplot as plt
import pandas as pd


# Connect to the KAPy database
conn = sqlite3.connect("./outputs/KAPy_database.sqlite")

# Select annual mean temperature for the ensemble median
query = """
SELECT *
FROM View_EnsembleArealStatistics
WHERE IndicatorCode = '101'
  AND StatisticTypeCode = 'mean'
  AND Percentile = 50
  AND Delta = 1
  AND SeasonCode = 'ann'
  AND TimeBinCode = '2071-01-01/2101-01-01'
  AND ScenarioCode = 'historical+rcp85'
"""

dat = pd.read_sql(query, conn)

# Import areas
areas = pd.read_sql(
    "SELECT * FROM Areas",
    conn,
)
areas["geometry"] = gpd.GeoSeries.from_wkt(areas["geom_wkt"])

conn.close()

# Add area information to the indicator results
dat = dat.merge(
    areas,
    on="AreaKey",
    how="left",
)

#Convert to geopandas
plt_dat = gpd.GeoDataFrame(
    dat,
    geometry="geometry",
    crs=areas["geom_crs"].iloc[0],
)


#plot
fig, ax = plt.subplots(figsize=(10, 10))

plt_dat.plot(
    column="Value",
    cmap="viridis",
    legend=True,
    ax=ax,
)

ax.set_title("Change in annual mean temperature, 2071–2100 vs 1981-2010")
ax.set_axis_off()

plt.tight_layout()
plt.show()