# This YAML file defines all requirements needed by KAPy. Note that it is
# specified without version numbers, so that the very latested versions of each
# package can be used. It's counterpart file is env.yaml which has the exact
# version numbers used in a specific installation of KAPy.
#
# The basic approach is to first create an environment encompassing all packages
#
# conda env create -f requirements.yaml
#
# The resulting environment, called KAPy, with all dependencies and version numbers can then 
# exported back to dev.yaml like so:
#
# conda env export > env.yaml
#
# The environment given here contains packages that are used for development purposes, but
# if you are only using KAPy for production, they are not strictly necessary and can be removed
# as follows:
#
# conda remove pre-commit ipykernel jsonschema2md
#
# Previous versions of KAPy have distinguished between the two environments but this functionality
# was remove for the sake of simplicity.
#
name: KAPy
channels:
  - bioconda
  - conda-forge
  - nodefaults
dependencies:
  - geopandas
  - netcdf4
  - pandas
  - python
  - python-cdo
  - snakemake
  - xarray
  - xesmf
  - xclim
  - xsdba
  - yaml
  - zarr
  - git
  # ----- Dev packages below this line ----------
  - cookiecutter
  - pre-commit   #Linting etc
  - ipykernel  #Used by vscode to provide a REPL for interactive debugging
  - jsonschema2md #Convert jsonschema to markdown documentation
  - pip
  - pip:
    - snakemake-logger-plugin-snkmt  
    - earthkit-transforms
