# This YAML file defines the basic requirements needed by KAPy. Note that it is
# specified without version numbers, so that the very latested versions of each
# package can be used. It's counterpart file is env.yaml, which has the exact
# version numbers used in a specific installation of KAPy.
#
# This file can be used to generate a fresh conda environment like so:
#
# conda env create -f requirements.yaml
#
# The resulting environment with all dependencies and version numbers can then 
# exported back to env.yaml like so:
#
# conda env export > env.yaml
#
# A third yaml file, dev.yaml, contains an environment used for development purposes
#
name: KAPy
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - geopandas
  - snakemake
  - xarray
  - regionmask
  - netcdf4
  - zarr
  - xclim
  - python-cdo
  - plotnine
  - yaml
